LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    swim-pubsub:
      level: DEBUG

    proton:
      level: INFO

BROKER:
  host: "rabbitmq:5671"
  cert_db: "/secrets/broker/ca_certificate.pem"
  sasl_user: ${GEOFENCING_VIEWER_BROKER_USER}
  sasl_password: ${GEOFENCING_VIEWER_BROKER_PASS}


# Geofencing service
SUBSCRIPTION-MANAGER-API:
  host: "nginx:8443"
  https: true
  timeout: 30
  verify: "/secrets/web_server/ca_certificate.pem"
  username: ${GEOFENCING_VIEWER_GS_USER}
  password: ${GEOFENCING_VIEWER_GS_PASS}


INITIAL_UAS_ZONES_FILTER:
  airspaceVolume:
    polygon:
      - LAT: 50.901767
        LON: 4.371125
      - LAT: 50.866953
        LON: 4.224330
      - LAT: 50.788595
        LON: 4.342881
      - LAT: 50.846430
        LON: 4.535647
      - LAT: 50.901767
        LON: 4.371125
    lowerLimit: 0
    upperLimit: 100000
    lowerVerticalReference: 'WGS84'
    upperVerticalReference: 'WGS84'
  startDateTime: '2020-01-01T00:00:00+01:00'
  endDateTime: '2021-01-01T00:00:00+01:00'
  regions:
    - 1
  requestID: '1'

POLLING_INTERVAL_IN_SEC: 1
