LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    swim-pubsub:
      level: DEBUG

    proton:
      level: INFO

BROKER:
  host: "rabbitmq:5671"
  cert_db: "/secrets/broker/ca_certificate.pem"
  sasl_user: ${GEOFENCING_VIEWER_BROKER_USER}
  sasl_password: ${GEOFENCING_VIEWER_BROKER_PASS}


# Geofencing service
SUBSCRIPTION-MANAGER-API:
  host: "nginx:8443"
  https: true
  timeout: 30
  verify: "/secrets/web_server/ca_certificate.pem"
  username: ${GEOFENCING_VIEWER_GS_USER}
  password: ${GEOFENCING_VIEWER_GS_PASS}


INITIAL_UAS_ZONES_FILTER:
  airspaceVolume:
    horizontalProjection:
      type: 'Circle'
      center: [4.503788, 50.826384]
      radius: 20000
    uomDimensions: 'M'
    lowerLimit: 0
    upperLimit: 100000
    upperVerticalReference: 'AGL'
    lowerVerticalReference: 'AGL'
  startDateTime: '2010-01-01T00:00:00+01:00'
  endDateTime: '2030-01-01T00:00:00+01:00'
  regions:
    - 1


POLLING_INTERVAL_IN_SEC: 1
